version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: microfrontend-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - microfrontend-network

  api:
    build: ./api
    container_name: microfrontend-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - microfrontend-network


  auth:
    build: ./auth
    container_name: microfrontend-auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - microfrontend-network

  api_db:
    container_name: microfrontend-api-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    networks:
      - microfrontend-network

  auth_db:
    container_name: microfrontend-auth-db
    image: mongo:latest
    volumes:
      - mongodb_auth:/data/db
    networks:
      - microfrontend-network      
  
  nginx:
    container_name: microfrontend-nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - microfrontend-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  microfrontend-network:
    driver: bridge