version: '3'

services:
  api:
    build: ./api
    container_name: microfrontend-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=stas.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  auth:
    build: ./auth
    container_name: microfrontend-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=stas.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    container_name: microfrontend-api-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
  
  auth_db:
    container_name: microfrontend-auth-db
    image: mongo:latest
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:
